backend:
  name: github
  repo: lassediercks/schubrakede-gridsome

media_folder: "static/img"
public_folder: "img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { name: description, widget: string }
          - {
              name: companies,
              widget: list,
              fields: [{ name: Image, widget: image }],
            }
          - { name: missiontext, widget: markdown }
          - { name: sprinttext, widget: markdown }
          - { name: handsOnText, widget: markdown }
          - {
              name: teammember,
              widget: list,
              fields:
                [
                  { name: Name, widget: string },
                  { name: Description, widget: string },
                  { name: Title, widget: string },
                  { name: Image, widget: image },
                ],
            }
      - label: "Impressum"
        name: imprint
        file: "content/pages/imprint.md"
        fields:
          - { name: "Title", widget: string }
          - { name: Content, widget: markdown }
      - label: "Datenschutz"
        name: datenschutz
        file: "content/pages/datenschutz.md"
        fields:
          - { name: "Title", widget: string }
          - { name: Content, widget: markdown }

  - name: "blog"
    label: "Blog"
    identifier_field: headline
    create: true
    folder: "content/blog"
    fields:
      - { name: headline, widget: string }
      - { name: content, widget: markdown }
