backend:
  name: github
  repo: lassediercks/schubrakede-next

media_folder: static/img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { name: description, widget: string }
          - { name: missiontext, widget: markdown }
          - { name: sprinttext, widget: markdown }
      - label: "Impressum"
        name: imprint
        file: "conntent/imprint.md"
        fields: 
          - { name: "Title", widget: string}
          
  - name: "blog"
    label: "Blog"
    identifier_field: headline
    create: true
    folder: "content/blog"
    fields:
      - { name: headline, widget: string }
      - { name: content, widget: markdown }
