backend:
  name: github
  repo: Schubrakede/schubrakede.de

display_url: https://schubrake.de
logo_url: https://schubrake.de/schubrakede.png
media_folder: "static/img"
public_folder: "img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/index.md"
        fields:
          - { label: "Name", name: "Name", widget: string }
          - { label: "Title", name: "title", widget: "string" }
          - { name: description, widget: string }
          - {
              name: companies,
              widget: list,
              fields: [{ name: Image, widget: image }],
            }
          - { name: missiontext, widget: markdown }
          - { name: handsOnText, widget: markdown }
          - {
              name: teammember,
              widget: list,
              fields:
                [
                  { name: Name, widget: string },
                  { name: Description, widget: string },
                  { name: Title, widget: string },
                  { name: Image, widget: image },
                ],
            }
      - label: "Impressum"
        name: imprint
        file: "content/pages/imprint.md"
        fields:
          - { name: "Title", widget: string }
          - { name: Content, widget: markdown }
      - label: "Datenschutz"
        name: datenschutz
        file: "content/pages/datenschutz.md"
        fields:
          - { name: "Title", widget: string }
          - { name: Content, widget: markdown }

  - name: "blog"
    label: "Blog"
    identifier_field: headline
    create: true
    editor:
      preview: false
    folder: "content/blog"
    fields:
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: false,
        }
      - { label: Date, name: date, widget: datetime }

      - { name: headline, widget: string }
      - { name: content, widget: markdown }
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "author"
        searchFields: ["name"]
        valueField: twitterhandle
        displayFields: ["name"]

  - name: "landingpage"
    label: "Landingpage"
    identifier_field: headline
    create: true
    folder: "content/landingpage"
    fields:
      - { name: headline, widget: string }
      - { name: subline, widget: string }
      - {
          name: features,
          widget: list,
          fields:
            [
              { name: image, widget: image },
              { name: headline, widget: string },
              { name: description, widget: text },
            ],
        }
      - {
          name: testimonial,
          widget: list,
          fields:
            [
              { name: quote, widget: text },
              { name: name, widget: string },
              { name: title, widget: string },
            ],
        }

  - name: "author"
    label: Author
    create: true
    identifier_field: twitterhandle
    folder: "content/author"
    slug: "{{slug}}"
    fields:
      - { name: name, widget: string }
      - { name: description, widget: string }
      - { name: image, widget: image }
      - { name: twitterhandle, widget: string }

  - name: product
    label: Product
    create: true
    identifier_field: name
    folder: "content/products"
    fields:
      - { name: published, widget: boolean, default: false }
      - { name: name, widget: string }
      - { name: duration, widget: string }
      - { name: locationInfo, widget: string }
      - { name: teaser, widget: string }
      - { name: description, widget: markdown }
      - { name: possibleOutcome, widget: markdown }
      - { name: additionalInformation, widget: markdown }
